backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "recettes"
    label: "Recettes"
    folder: "content/recettes"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Catégorie", name: "category", widget: "select", options: ["petit-dejeuner", "dejeuner", "diner", "collation", "dessert"] }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Temps de préparation", name: "time", widget: "string" }
      - { label: "Difficulté", name: "difficulty", widget: "select", options: ["Facile", "Moyen", "Difficile"] }
      - { label: "Calories", name: "calories", widget: "string" }
      - { label: "Protéines", name: "protein", widget: "string" }
      - { label: "Glucides", name: "carbs", widget: "string" }
      - { label: "Lipides", name: "fat", widget: "string" }
      - label: "Ingrédients"
        name: "ingredients"
        widget: "list"
        field: { label: "Ingrédient", name: "item", widget: "string" }
      - label: "Instructions"
        name: "instructions"
        widget: "list"
        field: { label: "Étape", name: "step", widget: "text" }

site_url: "https://mathildejoyeux.netlify.app"
display_url: "https://mathildejoyeux.netlify.app"
locale: "fr"
