backend:
  name: git-gateway
  branch: main

# CORRECTION : Supprimez le sous-dossier "uploads"
media_folder: "images"  # juste "images" au lieu de "images/uploads"
public_folder: "/images"  # juste "/images" au lieu de "/images/uploads"

collections:
  - name: "recettes"
    label: "Recettes"
    folder: "content/recettes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Catégorie", name: "category", widget: "select", options: ["petit-dejeuner", "dejeuner", "diner", "collation", "dessert"] }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Temps de préparation", name: "time", widget: "string" }
      - { label: "Difficulté", name: "difficulty", widget: "select", options: ["Facile", "Moyen", "Difficile"] }
      - { label: "Calories", name: "calories", widget: "string" }
      - { label: "Protéines", name: "protein", widget: "string" }
      - { label: "Glucides", name: "carbs", widget: "string" }
      - { label: "Lipides", name: "fat", widget: "string" }
      - label: "Ingrédients"
        name: "ingredients"
        widget: "list"
        fields:
          - { label: "Ingrédient", name: "item", widget: "string" }
      - label: "Instructions"
        name: "instructions"
        widget: "list"
        fields:
          - { label: "Étape", name: "step", widget: "text" }